src/Entity/Traitement.php
<?php

namespace App\Entity;

use App\Repository\TraitementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TraitementRepository::class)
 */
class Traitement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="traitements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Collaborateur;

    /**
     * @ORM\Column(type="integer")
     */
    private $TicketNumber;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Traitement = null;


    public function __construct()
    {
        $this->CreatedAt = new \Datetime();
    }

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Comment;

    /**
     * @ORM\Column(type="boolean")
     */
    private $DejaTraite = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCollaborateur(): ?User
    {
        return $this->Collaborateur;
    }

    public function setCollaborateur(?User $Collaborateur): self
    {
        $this->Collaborateur = $Collaborateur;

        return $this;
    }

    public function getTicketNumber(): ?int
    {
        return $this->TicketNumber;
    }

    public function setTicketNumber(int $TicketNumber): self
    {
        $this->TicketNumber = $TicketNumber;

        return $this;
    }

    public function getTraitement(): ?bool
    {
        return $this->Traitement;
    }

    public function setTraitement(?bool $Traitement): self
    {
        $this->Traitement = $Traitement;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->Comment;
    }

    public function setComment(?string $Comment): self
    {
        $this->Comment = $Comment;

        return $this;
    }

    public function getDejaTraite(): ?bool
    {
        return $this->DejaTraite;
    }

    public function setDejaTraite(bool $DejaTraite): self
    {
        $this->DejaTraite = $DejaTraite;

        return $this;
    }
}

src/Form/TraitementType.php
<?php

namespace App\Form;

use App\Entity\Traitement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TraitementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('TicketNumber', NumberType::class, [
                'label' => 'Numéro du ticket traité',
                'attr'      => array('class' => 'form-control'),
            ])
            ->add('Traitement', ChoiceType::class, [
                'required' => true,
                'label'  => 'Traitement réalisé' ,
                'expanded'  => false,
                'multiple'  => false,
                'attr'      => array('class' => 'form-check-input'),
                'choices'  => [
                    'Traitement fait ?' => "",
                    'Oui' => 1,
                    'Non' => 0,
                ]])
            ->add('Comment', TextareaType::class, [
                'label' => 'Indiquer un commentaire si nécessaire',
                'required' => false,
                'attr'      => array('class' => 'form-control'),
            ])
            ->add('DejaTraite', ChoiceType::class, [
                'required' => true,
                'label'  => 'Ticket déjà traité' ,
                'expanded'  => false,
                'multiple'  => false,
                'attr'      => array('class' => 'form-check-input'),
                'choices'  => [
                    'Oui' => 1,
                    'Non' => 0,
                ]])
            ->remove('CreatedAt')
            ->remove('Collaborateur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Traitement::class,
        ]);
    }
}

src/Controller/TraitementController.php
<?php

namespace App\Controller;

use App\Entity\Traitement;
use App\Form\TraitementType;
use App\Repository\TraitementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/traitement")
 */
class TraitementController extends AbstractController
{
    /**
     * @Route("/", name="traitement_index", methods={"GET"})
     */
    public function index(TraitementRepository $traitementRepository): Response
    {
        return $this->render('traitement/index.html.twig', [
            'traitements' => $traitementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="traitement_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $traitement = new Traitement();
        $traitement->setCollaborateur($this->getUser());
        $form = $this->createForm(TraitementType::class, $traitement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($traitement);
            $entityManager->flush();


            $this->addFlash('success', 'Traitement enregistré');
            return $this->redirectToRoute('traitement_new');
        }

        return $this->render('traitement/new.html.twig', [
            'traitement' => $traitement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="traitement_show", methods={"GET"})
     */
    public function show(Traitement $traitement): Response
    {
        return $this->render('traitement/show.html.twig', [
            'traitement' => $traitement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="traitement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Traitement $traitement): Response
    {
        $form = $this->createForm(TraitementType::class, $traitement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('traitement_index');
        }

        return $this->render('traitement/edit.html.twig', [
            'traitement' => $traitement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="traitement_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Traitement $traitement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$traitement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($traitement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('traitement_index');
    }
}

templates/traitement/_delete_form.html.twig
<form method="post" action="{{ path('traitement_delete', {'id': traitement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ traitement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/traitement/_form.html.twig
{{ form_start(form, {'attr': {'class': 'form', 'role' : 'form'}}) }}
<div class="form">

    <div class="form-group row">
        <label for="TicketNumber" class="col-sm-4 col-form-label">{{ form_label(form.TicketNumber) }}</label>
        <div class="col-sm-8">
            {{ form_errors(form.TicketNumber) }}
            {{ form_widget(form.TicketNumber) }}
        </div>
    </div>

    <div class="form-group row">
        <label for="Traitement" class="col-sm-4 col-form-label">{{ form_label(form.Traitement) }}</label>
        <div class="col-sm-8 ">
            {{ form_errors(form.Traitement) }}
            {{ form_widget(form.Traitement) }}
        </div>
    </div>

    <div class="form-group row">
        <label for="Comment" class="col-sm-4 col-form-label">{{ form_label(form.Comment) }}</label>
        <div class="col-sm-8">
            {{ form_errors(form.Comment) }}
            {{ form_widget(form.Comment) }}
        </div>
    </div>

    <div class="form-group row">
        <label for="DejaTraite" class="col-sm-4 col-form-label">{{ form_label(form.DejaTraite) }}</label>
        <div class="col-sm-8 ">
            {{ form_errors(form.DejaTraite) }}
            {{ form_widget(form.DejaTraite) }}
        </div>
    </div>



<button class="btn btn-success">{{ button_label|default('Valider Traitement') }}</button>

{{ form_end(form) }}

templates/traitement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Traitement{% endblock %}

{% block body %}
    <h1>Edit Traitement</h1>

    {{ include('traitement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('traitement_index') }}">back to list</a>

    {{ include('traitement/_delete_form.html.twig') }}
{% endblock %}

templates/traitement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Traitement index{% endblock %}

{% block body %}
    <h1>Traitement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>TicketNumber</th>
                <th>Traitement</th>
                <th>CreatedAt</th>
                <th>actions</th>
                <th>Déjà traite</th>
                <th>Commentaire</th>
            </tr>
        </thead>
        <tbody>
        {% for traitement in traitements %}
            <tr>
                <td>{{ traitement.id }}</td>
                <td>{{ traitement.TicketNumber }}</td>
                <td>{{ traitement.Traitement ? 'Yes' : 'No' }}</td>
                <td>{{ traitement.CreatedAt ? traitement.CreatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ traitement.DejaTraite ? 'Yes' : 'No' }}</td>
                <td>{{ traitement.comment }}</td>
                <td>
                    <a href="{{ path('traitement_show', {'id': traitement.id}) }}">show</a>
                    <a href="{{ path('traitement_edit', {'id': traitement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('traitement_new') }}">Create new</a>
{% endblock %}

templates/traitement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Traitement{% endblock %}

{% block body %}
    <div class="jumbutron">
        <h1>Ajouter un traitement</h1>
    </div>

    <div class="row">
        <div class="col-6 mx-auto">
            {{ include('traitement/_form.html.twig') }}
        </div>

    </div>
    {% if is_granted("ROLE_ADMIN") %}
    <a href="{{ path('traitement_index') }}">back to list</a>
    {% endif %}
{% endblock %}

templates/traitement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Traitement{% endblock %}

{% block body %}
    <h1>Traitement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ traitement.id }}</td>
            </tr>
            <tr>
                <th>TicketNumber</th>
                <td>{{ traitement.TicketNumber }}</td>
            </tr>
            <tr>
                <th>Traitement</th>
                <td>{{ traitement.Traitement ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ traitement.CreatedAt ? traitement.CreatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ traitement.CreatedAt ? traitement.CreatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('traitement_index') }}">back to list</a>

    <a href="{{ path('traitement_edit', {'id': traitement.id}) }}">edit</a>

    {{ include('traitement/_delete_form.html.twig') }}
{% endblock %}